/**
 * PROTOTYPE — throwaway. Fixture venues for the desktop-map design spike, so the variants render
 * at realistic density with no backend running. Eighteen venues strung along the real coast, in
 * the catalogue's canonical north-to-south order (`shared/beaches.ts`), with hand-set coordinates
 * near each beach's recorded camera centre.
 *
 * Deliberately NOT fed through `VenueService`: the question this spike answers is "where does the
 * map go on desktop", and a fixture keeps `npm start` enough to see it.
 */
import { VenueCard } from '../home/venue-card';
import { BeachCode, beachEntry, beachLabel, regionLabel } from '../../shared/beaches';
import { Amenity, amenityLabel } from '../../shared/amenities';

interface Seed {
  readonly name: string;
  readonly beach: BeachCode;
  readonly lng: number;
  readonly lat: number;
  /** Tenths, as the API sends them; `null` for an unrated venue. */
  readonly rating: number | null;
  readonly reviews: number;
  readonly request?: true;
  /** From-price in minor units (EUR), invariant #5 — integer, never a float. */
  readonly price: number;
  readonly free: number;
  readonly total: number;
  readonly water: string | null;
  readonly amenities: readonly Amenity[];
  readonly photos: number;
}

const SEEDS: readonly Seed[] = [
  {
    name: 'Velipoja Lido',
    beach: 'VELIPOJE',
    lng: 19.4029,
    lat: 41.8551,
    rating: 41,
    reviews: 64,
    price: 1400,
    free: 22,
    total: 40,
    water: '20 m to water',
    amenities: ['BEACH_BAR', 'FREE_PARKING', 'SHOWERS'],
    photos: 2,
  },
  {
    name: 'Rana e Hedhun',
    beach: 'SHENGJIN',
    lng: 19.5916,
    lat: 41.8128,
    rating: 45,
    reviews: 212,
    price: 1800,
    free: 9,
    total: 30,
    water: '35 m to water',
    amenities: ['RESTAURANT', 'WIFI', 'SHOWERS'],
    photos: 3,
  },
  {
    name: 'Cape Rodon Club',
    beach: 'LALEZ',
    lng: 19.4954,
    lat: 41.4649,
    rating: 43,
    reviews: 51,
    request: true,
    price: 2100,
    free: 14,
    total: 18,
    water: '15 m to water',
    amenities: ['QUIET_BAY', 'SNORKELLING'],
    photos: 1,
  },
  {
    name: 'Currila Sunset',
    beach: 'CURRILA',
    lng: 19.4355,
    lat: 41.3316,
    rating: 38,
    reviews: 27,
    price: 1600,
    free: 31,
    total: 44,
    water: '60 m to water',
    amenities: ['CAFE', 'FREE_PARKING'],
    photos: 2,
  },
  {
    name: 'Golem Beach House',
    beach: 'GOLEM',
    lng: 19.5159,
    lat: 41.24,
    rating: 42,
    reviews: 380,
    price: 1500,
    free: 4,
    total: 52,
    water: '25 m to water',
    amenities: ['BEACH_BAR', 'WATER_SPORTS', 'SHOWERS'],
    photos: 3,
  },
  {
    name: 'Qerret Riva',
    beach: 'QERRET',
    lng: 19.5011,
    lat: 41.2132,
    rating: 40,
    reviews: 96,
    price: 1700,
    free: 26,
    total: 36,
    water: '30 m to water',
    amenities: ['RESTAURANT', 'PET_FRIENDLY'],
    photos: 1,
  },
  {
    name: 'Zvërnec Lagoon',
    beach: 'ZVERNEC',
    lng: 19.4212,
    lat: 40.5109,
    rating: 47,
    reviews: 73,
    request: true,
    price: 2400,
    free: 6,
    total: 14,
    water: '10 m to water',
    amenities: ['QUIET_BAY', 'CAFE'],
    photos: 2,
  },
  {
    name: 'Radhimë Rocks',
    beach: 'RADHIME',
    lng: 19.4809,
    lat: 40.3606,
    rating: 44,
    reviews: 118,
    price: 2200,
    free: 17,
    total: 28,
    water: '5 m to water',
    amenities: ['SNORKELLING', 'BEACH_BAR'],
    photos: 3,
  },
  {
    name: 'Palasa Sands',
    beach: 'PALASE',
    lng: 19.6013,
    lat: 40.1599,
    rating: 46,
    reviews: 143,
    price: 2600,
    free: 11,
    total: 26,
    water: '20 m to water',
    amenities: ['RESTAURANT', 'WIFI', 'FREE_PARKING'],
    photos: 2,
  },
  {
    name: 'Drymades Dune',
    beach: 'DRYMADES',
    lng: 19.6203,
    lat: 40.1484,
    rating: 48,
    reviews: 291,
    price: 3200,
    free: 3,
    total: 30,
    water: '15 m to water',
    amenities: ['BEACH_BAR', 'WATER_SPORTS'],
    photos: 3,
  },
  {
    name: 'Aurora Bay',
    beach: 'DHERMI',
    lng: 19.6407,
    lat: 40.1406,
    rating: 41,
    reviews: 88,
    request: true,
    price: 3000,
    free: 5,
    total: 10,
    water: '8 m to water',
    amenities: ['QUIET_BAY'],
    photos: 1,
  },
  {
    name: 'Folie Marine',
    beach: 'DHERMI',
    lng: 19.6402,
    lat: 40.1433,
    rating: 39,
    reviews: 402,
    price: 3900,
    free: 2,
    total: 34,
    water: '12 m to water',
    amenities: ['BEACH_BAR', 'RESTAURANT', 'WIFI'],
    photos: 3,
  },
  {
    name: 'Jalë Cove',
    beach: 'JALE',
    lng: 19.6999,
    lat: 40.1173,
    rating: 43,
    reviews: 64,
    price: 2300,
    free: 19,
    total: 24,
    water: '18 m to water',
    amenities: ['SNACK_SHACK', 'SHOWERS'],
    photos: 2,
  },
  {
    name: 'Livadhi Long Beach',
    beach: 'LIVADHI',
    lng: 19.7252,
    lat: 40.1082,
    rating: 40,
    reviews: 35,
    price: 1900,
    free: 28,
    total: 46,
    water: '40 m to water',
    amenities: ['FREE_PARKING', 'CAFE'],
    photos: 1,
  },
  {
    name: 'Borsh Olive Shore',
    beach: 'BORSH',
    lng: 19.8521,
    lat: 40.0453,
    rating: null,
    reviews: 0,
    price: 1700,
    free: 33,
    total: 42,
    water: '25 m to water',
    amenities: ['QUIET_BAY', 'PET_FRIENDLY'],
    photos: 2,
  },
  {
    name: 'Miramar Beach Club',
    beach: 'KSAMIL',
    lng: 20.0016,
    lat: 39.7726,
    rating: 48,
    reviews: 326,
    price: 2500,
    free: 18,
    total: 24,
    water: '10 m to water',
    amenities: ['BEACH_BAR', 'RESTAURANT', 'WATER_SPORTS'],
    photos: 3,
  },
  {
    name: 'Lori Beach',
    beach: 'KSAMIL',
    lng: 20.0042,
    lat: 39.7724,
    rating: 40,
    reviews: 15,
    price: 2100,
    free: 15,
    total: 25,
    water: '22 m to water',
    amenities: ['SHOWERS', 'SNACK_SHACK'],
    photos: 2,
  },
  {
    name: 'Pasqyra Blue',
    beach: 'PASQYRA',
    lng: 20.0131,
    lat: 39.8,
    rating: 44,
    reviews: 129,
    request: true,
    price: 2800,
    free: 7,
    total: 16,
    water: '6 m to water',
    amenities: ['SNORKELLING', 'QUIET_BAY'],
    photos: 1,
  },
  {
    name: 'Shëngjin Marina',
    beach: 'SHENGJIN',
    lng: 19.5946,
    lat: 41.8105,
    rating: 39,
    reviews: 44,
    price: 1600,
    free: 12,
    total: 34,
    water: '50 m to water',
    amenities: ['RESTAURANT', 'FREE_PARKING'],
    photos: 2,
  },
  {
    name: 'Golem Sun Deck',
    beach: 'GOLEM',
    lng: 19.5145,
    lat: 41.2376,
    rating: 37,
    reviews: 61,
    price: 1300,
    free: 40,
    total: 58,
    water: '45 m to water',
    amenities: ['SNACK_SHACK', 'SHOWERS'],
    photos: 1,
  },
  {
    name: 'Golem Aqua',
    beach: 'GOLEM',
    lng: 19.5161,
    lat: 41.2399,
    rating: 42,
    reviews: 154,
    request: true,
    price: 1900,
    free: 8,
    total: 20,
    water: '15 m to water',
    amenities: ['WATER_SPORTS', 'BEACH_BAR'],
    photos: 3,
  },
  {
    name: 'Dhërmi Sun Club',
    beach: 'DHERMI',
    lng: 19.6407,
    lat: 40.1406,
    rating: 38,
    reviews: 9,
    request: true,
    price: 2400,
    free: 19,
    total: 22,
    water: '30 m to water',
    amenities: ['CAFE'],
    photos: 2,
  },
  {
    name: 'Palasa Pine',
    beach: 'PALASE',
    lng: 19.6013,
    lat: 40.1599,
    rating: null,
    reviews: 0,
    price: 2200,
    free: 24,
    total: 28,
    water: '35 m to water',
    amenities: ['QUIET_BAY', 'FREE_PARKING'],
    photos: 1,
  },
  {
    name: 'Ksamil Three Islands',
    beach: 'KSAMIL',
    lng: 20.0025,
    lat: 39.7684,
    rating: 46,
    reviews: 511,
    price: 3400,
    free: 6,
    total: 48,
    water: '5 m to water',
    amenities: ['BEACH_BAR', 'SNORKELLING', 'RESTAURANT'],
    photos: 3,
  },
  {
    name: 'Borsh Kilometre',
    beach: 'BORSH',
    lng: 19.851,
    lat: 40.0458,
    rating: 42,
    reviews: 78,
    price: 1500,
    free: 47,
    total: 60,
    water: '30 m to water',
    amenities: ['FREE_PARKING', 'SNACK_SHACK'],
    photos: 2,
  },
  {
    name: 'Jalë Rocks',
    beach: 'JALE',
    lng: 19.6999,
    lat: 40.1158,
    rating: 44,
    reviews: 96,
    price: 2700,
    free: 4,
    total: 18,
    water: '10 m to water',
    amenities: ['SNORKELLING', 'CAFE'],
    photos: 1,
  },
];

/** A stand-in photo per slot; the screenshot driver answers these paths with generated beach JPEGs. */
function photos(id: number, count: number): VenueCard['photos'] {
  return Array.from({ length: count }, (_, slot) => {
    const url = `/api/venues/${id}/photos/ph${id}${'abc'[slot]}`;
    return { url, sources: [{ url, width: 576 }] };
  });
}

/** The fixture as ready-made Discover cards — the same view model `pages/home` renders. */
export const PROTOTYPE_VENUES: readonly VenueCard[] = SEEDS.map((seed, i) => {
  const id = i + 1;
  return {
    id,
    name: seed.name,
    beach: seed.beach,
    beachLabel: beachLabel(seed.beach),
    // The region is the catalogue's answer for the beach, never restated in the seed.
    regionLabel: regionLabel(beachEntry(seed.beach)!.region),
    photos: photos(id, seed.photos),
    modeLabel: seed.request ? 'Request to Book' : 'Instant Book',
    isRated: seed.rating !== null,
    rating: seed.rating === null ? '' : (seed.rating / 10).toFixed(1),
    reviewsLabel: seed.reviews === 1 ? '1 review' : `${seed.reviews} reviews`,
    water: seed.water,
    amenities: seed.amenities.map((code) => ({ code, label: amenityLabel(code) })),
    freePercent: Math.round((seed.free / seed.total) * 100),
    priceLabel: `€${(seed.price / 100).toFixed(0)}`,
    fromPrice: { minorUnits: seed.price, currency: 'EUR' },
    free: seed.free,
    total: seed.total,
    salesClosed: false,
    closedForSeason: false,
    reopensOn: null,
    location: { latitude: seed.lat, longitude: seed.lng },
    ariaLabel: `${seed.name}, ${beachLabel(seed.beach)}`,
  } satisfies VenueCard;
});
